workflows:
  ios-test-build:
    name: iOS Test Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app (unsigned)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/*.dSYM
    publishing:
      email:
        recipients:
          - zenonroboticsco@gmail.com
        notify:
          success: true
          failure: true
