# ============================================================================
# CODEMAGIC YAML - ZENON ROBOT APP
# Fixed iOS Build Configuration with Deployment Target Fix
# ============================================================================

workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Fix iOS deployment target
        script: |
          # Fix Podfile to use iOS 12.0 minimum
          cat > ios/Podfile << 'EOF'
          # Uncomment this line to define a global platform for your project
          platform :ios, '12.0'

          # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                # Set minimum deployment target to iOS 12.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
            end
          end
          EOF
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign
      
      - name: Create unsigned IPA manually
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../zenon-robot-unsigned.ipa Payload/
          rm -rf Payload
          cd ../../..
    
    artifacts:
      - zenon-robot-unsigned.ipa
      - build/ios/iphoneos/*.dSYM
    
    publishing:
      email:
        recipients:
          - zenonroboticsco@gmail.com
        notify:
          success: true
          failure: true


# ============================================================================
# OPTION 2: SIGNED BUILD (RECOMMENDED - Fully Installable)
# ============================================================================
  ios-signed:
    name: iOS Signed Build (Ad-Hoc)
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.zenonrobotics.zenonrobotapp
      
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    
    scripts:
      - name: Fix iOS deployment target
        script: |
          # Fix Podfile to use iOS 12.0 minimum
          cat > ios/Podfile << 'EOF'
          platform :ios, '12.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
            end
          end
          EOF
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            "com.zenonrobotics.zenonrobotapp" \
            --type IOS_APP_ADHOC \
            --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd ios
          agvtool new-version -all $(($(date +%s) / 60))
          cd ..
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build signed iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.dSYM
    
    publishing:
      email:
        recipients:
          - zenonroboticsco@gmail.com
        notify:
          success: true
          failure: true


# ============================================================================
# OPTION 3: APP STORE BUILD (Production)
# ============================================================================
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zenonrobotics.zenonrobotapp
      
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APPLE_ID: 1234567890
    
    scripts:
      - name: Fix iOS deployment target
        script: |
          cat > ios/Podfile << 'EOF'
          platform :ios, '12.0'
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }

          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
            end

            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
          end

          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

          flutter_ios_podfile_setup

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
            end
          end
          EOF
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            "com.zenonrobotics.zenonrobotapp" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Set build version
        script: |
          cd ios
          VERSION=${CM_TAG#v}
          agvtool new-marketing-version $VERSION
          agvtool new-version -all $CM_BUILD_NUMBER
          cd ..
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build App Store IPA
        script: |
          flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.dSYM
    
    publishing:
      email:
        recipients:
          - zenonroboticsco@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
